title: Ben Balter
description: Attorney, open source developer, product manager

lang: en-US
branch: master

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md

footer_pages:
  - fine-print.md

# Disqus login information, for comments
disqus:
  shortname: DISQUS_USERNAME

# Google Analytics tracking id
ga_username: UA-xxxxxxxx-x

# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/BenBalter
    icon: twitter
  - name: Facebook
    url: https://facebook.com/BenBalter
    icon: facebook

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

plugins:
  # - jekyll-seo-tag
  # - jekyll-github-metadata
  # - jekyll-feed
  # - jekyll-include-cache
  - jekyll-spaceship
  - urlcrypt
  - jekyll-polyglot

exclude:
  - vendor/bundle
  - node_modules
  - js
  - sass

theme: null
includes_dir: /etc
PWNTESTER: rules!


collections:
  test_col:
    output: true
    collections_dir: ../_test-col

kramdown:
  coderay:
    coderay_formatter: Hoosegow
    coderay_inmate_dir: /tmp/
